using AwadyLab.EFCatalyst.Extensions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using SampleApp.Domain;
using SampleApp.Infrastructure;

namespace SampleApp.Scenarios;

/// <summary>
/// Migration helpers: the operations a migration's <c>Up()</c> would call, rendered by the provider package and
/// executed here directly so their effect is visible.
/// </summary>
public sealed class MigrationHelpersScenario : IScenario
{
    public string Name => "migrations";

    public string Title => "Migration helpers: idempotent data, indexes and triggers";

    public async Task RunAsync(SampleHost host)
    {
        await using var session = host.Open();
        var db = session.Db;
        var orders = db.GetTableName<Order>();

        // In a real migration: protected override void Up(MigrationBuilder migrationBuilder) { ... }
        var migration = new MigrationBuilder(activeProvider: null);
        migration.UpsertData(db.GetTableName<Category>(), ["Id"], ["Id", "Name", "IsArchived"],
            new object?[,] { { 5, "Mobile phones", false }, { 7, "Tablets", false } });
        migration.CreateSoftDeleteIndex(orders);
        migration.AddSoftDeleteTrigger(orders);

        Output.Step("SQL generated by the SQLite package (identifiers quoted, values as literals)");
        var commands = db.GetService<IMigrationsSqlGenerator>().Generate(migration.Operations, db.Model);
        foreach (var command in commands)
        {
            var text = string.Join(' ', command.CommandText.Split([' ', '\r', '\n'], StringSplitOptions.RemoveEmptyEntries));
            Output.Line(text.Length > 110 ? text[..110] + "…" : text);
            await db.Database.ExecuteSqlRawAsync(command.CommandText);
        }

        Output.Line($"categories after upsert: {string.Join(", ", await db.Categories.Where(c => c.Id >= 5).Select(c => c.Name).ToListAsync())}");

        Output.Step("The trigger turns even a raw DELETE into a soft delete");
        db.Orders.Add(new Order(1, 1, 10m));
        await db.SaveChangesAsync();
        var deleteAll = $"DELETE FROM {db.GetDelimitedTableName<Order>()}";
        await db.Database.ExecuteSqlRawAsync(deleteAll);
        Output.Line($"visible orders: {await db.Orders.CountAsync()}, soft-deleted: {await db.Orders.OnlySoftDeleted().CountAsync()}");
    }
}
